# Generated by Django 5.1.1 on 2024-09-21 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("election", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("student_id", models.CharField(max_length=50)),
                ("previous_hash", models.CharField(max_length=64)),
                ("hash", models.CharField(max_length=64)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="election.candidate",
                        to_field="candidate_key",
                    ),
                ),
            ],
        ),
    ]
