# Generated by Django 5.1.1 on 2024-09-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="student_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
