# Generated by Django 5.1.1 on 2024-10-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0002_candidate_image"),
        ("voting", "0002_alter_vote_student_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vote",
            name="candidate",
        ),
        migrations.AddField(
            model_name="vote",
            name="candidates",
            field=models.ManyToManyField(to="election.candidate"),
        ),
        migrations.AlterField(
            model_name="vote",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
