# Generated by Django 5.1.1 on 2024-09-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("election", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="candidate_images/"
            ),
        ),
    ]
